# application-env.yml — centralized environment / defaults (replace with secure values per environment)
# Developer note: this file provides local defaults for development. Do NOT commit production secrets.

CP_CDK_DATASOURCE_URL: jdbc:postgresql://db:55432/casedocumentknowledgeDatabase
CP_CDK_DATASOURCE_USERNAME: casedocumentknowledge
CP_CDK_DATASOURCE_PASSWORD: casedocumentknowledge
SERVER_PORT: 8082
SERVER_SERVLET_CONTEXT_PATH: /casedocumentknowledge-service
SPRING_APPLICATION_NAME: cp-case-document-knowledge-service
CP_CDK_ARTEMIS_URL: tcp://artemis:61616
CP_CDK_REST_SPECIFICATION: case-admin-doc-knowledge-api.openapi.yml

# Optional: debug
LOGGING_LEVEL_org.flywaydb: "DEBUG"
MANAGEMENT_TRACING_ENABLED: "false"     # <— Spring relaxed binding for management.tracing.enabled
TRACING_ENABLED: "false"                # <— matches the placeholder in application.yml

CP_CDK_DB_POOL_SIZE: 20
CP_CDK_DB_MIN_IDLE: 5


MANAGEMENT_SERVER_PORT: 8082

CLUSTER_NAME: local
REGION: local

TRACING_SAMPLER_PROBABILITY: 1.0
OTEL_METRICS_ENABLED: false
OTEL_TRACES_URL: http://localhost:4318/traces
OTEL_METRICS_URL: http://localhost:4318/metrics

CP_CDK_AZURE_STORAGE_CONNECTION_STRING: zzzz
CP_CDK_AZURE_STORAGE_CONTAINER: documents

CP_CDK_RAG_URL: https://spnl-apim-int-gw.cpp.nonlive/api-cp-ai-rag
CP_CDK_RAG_SUBSCRIPTION_KEY: FOFF
CP_CDK_CJSCPPUID_HEADER: CJSCPPUID
CP_CDK_PROGRESSION_BASE_URL: http://localhost:8089/progression-query-api
CP_CDK_HEARING_BASE_URL: http://localhost:8089/hearing-query-api

VIRTUAL_THREADS: false
